// Client-safe social media constants — no server imports
export const PLATFORM_CONFIGS = {
  FACEBOOK: {
    name: "Facebook",
    color: "#1877F2",
    bgColor: "bg-blue-600",
    charLimit: 63206,
    supportsImages: true,
    supportsVideos: true,
    supportsReels: false,
    supportsCarousel: false,
    requiresMedia: false,
    description: "Pages & profiles",
  },
  INSTAGRAM: {
    name: "Instagram",
    color: "#E1306C",
    bgColor: "bg-pink-600",
    charLimit: 2200,
    supportsImages: true,
    supportsVideos: true,
    supportsReels: true,
    supportsCarousel: true,
    requiresMedia: true,
    description: "Business accounts",
  },
  TWITTER: {
    name: "X (Twitter)",
    color: "#000000",
    bgColor: "bg-slate-900",
    charLimit: 280,
    supportsImages: true,
    supportsVideos: true,
    supportsReels: false,
    supportsCarousel: false,
    requiresMedia: false,
    description: "Tweet & threads",
  },
  LINKEDIN: {
    name: "LinkedIn",
    color: "#0077B5",
    bgColor: "bg-sky-700",
    charLimit: 3000,
    supportsImages: true,
    supportsVideos: true,
    supportsReels: false,
    supportsCarousel: false,
    requiresMedia: false,
    description: "Professional network",
  },
  TIKTOK: {
    name: "TikTok",
    color: "#010101",
    bgColor: "bg-neutral-900",
    charLimit: 2200,
    supportsImages: false,
    supportsVideos: true,
    supportsReels: true,
    supportsCarousel: false,
    requiresMedia: true,
    description: "Short videos & reels",
  },
  YOUTUBE: {
    name: "YouTube",
    color: "#FF0000",
    bgColor: "bg-red-600",
    charLimit: 5000,
    supportsImages: false,
    supportsVideos: true,
    supportsReels: true,
    supportsCarousel: false,
    requiresMedia: true,
    description: "Videos & Shorts",
  },
} as const
